/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommentsCtrl: typeof import('./src/components/CommentsCtrl.vue')['default']
    CommentsInfo: typeof import('./src/components/CommentsInfo.vue')['default']
    CommentsItem: typeof import('./src/components/CommentsItem.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VpHeader: typeof import('el-admin-components')['VpHeader']
    VpHeaderTabs: typeof import('el-admin-components')['VpHeaderTabs']
    VpMenu: typeof import('el-admin-components')['VpMenu']
    VpTable: typeof import('el-admin-components')['VpTable']
  }
}
