/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommentsCtrl: typeof import('./src/components/CommentsCtrl.vue')['default']
    CommentsInfo: typeof import('./src/components/CommentsInfo.vue')['default']
    CommentsItem: typeof import('./src/components/CommentsItem.vue')['default']
    ContentsDetail: typeof import('./src/pages/contents/contents-detail.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VpDescription: typeof import('el-admin-components')['VpDescription']
    VpForm: typeof import('el-admin-components')['VpForm']
    VpHeader: typeof import('el-admin-components')['VpHeader']
    VpHeaderTabs: typeof import('el-admin-components')['VpHeaderTabs']
    VpMenu: typeof import('el-admin-components')['VpMenu']
    VpTable: typeof import('el-admin-components')['VpTable']
    VpVueEcharts: typeof import('el-admin-components')['VpVueEcharts']
  }
}
