/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommentItem: typeof import('./src/components/comments/CommentItem.vue')['default']
    CommentsCtrl: typeof import('./src/components/CommentsCtrl.vue')['default']
    CommentsInfo: typeof import('./src/components/CommentsInfo.vue')['default']
    CommentsItem: typeof import('./src/components/CommentsItem.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    FilePreview: typeof import('./src/components/contents/upload/FilePreview.vue')['default']
    GeetestCaptcha: typeof import('./src/components/verification/GeetestCaptcha.vue')['default']
    JsonPreview: typeof import('./src/components/contents/JsonPreview.vue')['default']
    JsonPreviewPlus: typeof import('./src/components/contents/json/JsonPreviewPlus.vue')['default']
    MessageItem: typeof import('./src/components/messages/MessageItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TurnstileCaptcha: typeof import('./src/components/verification/TurnstileCaptcha.vue')['default']
    UploadTrigger: typeof import('./src/components/contents/upload/UploadTrigger.vue')['default']
    VpForm: typeof import('el-admin-components')['VpForm']
    VpHeader: typeof import('el-admin-components')['VpHeader']
    VpHeaderTabs: typeof import('el-admin-components')['VpHeaderTabs']
    VpMenu: typeof import('el-admin-components')['VpMenu']
    VpTable: typeof import('el-admin-components')['VpTable']
  }
}
