/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/contents': RouteRecordInfo<'/contents', '/contents', Record<never, never>, Record<never, never>>,
    '/contents/': RouteRecordInfo<'/contents/', '/contents', Record<never, never>, Record<never, never>>,
    '/contents/add-edit-form': RouteRecordInfo<'/contents/add-edit-form', '/contents/add-edit-form', Record<never, never>, Record<never, never>>,
    '/contents/content-detail': RouteRecordInfo<'/contents/content-detail', '/contents/content-detail', Record<never, never>, Record<never, never>>,
    '/contents/files': RouteRecordInfo<'/contents/files', '/contents/files', Record<never, never>, Record<never, never>>,
    '/contents/notes': RouteRecordInfo<'/contents/notes', '/contents/notes', Record<never, never>, Record<never, never>>,
    '/contents/pages': RouteRecordInfo<'/contents/pages', '/contents/pages', Record<never, never>, Record<never, never>>,
    '/contents/tags': RouteRecordInfo<'/contents/tags', '/contents/tags', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/login/forgot': RouteRecordInfo<'/login/forgot', '/login/forgot', Record<never, never>, Record<never, never>>,
    '/login/reg': RouteRecordInfo<'/login/reg', '/login/reg', Record<never, never>, Record<never, never>>,
    '/marketing': RouteRecordInfo<'/marketing', '/marketing', Record<never, never>, Record<never, never>>,
    '/marketing/': RouteRecordInfo<'/marketing/', '/marketing', Record<never, never>, Record<never, never>>,
    '/marketing/commision': RouteRecordInfo<'/marketing/commision', '/marketing/commision', Record<never, never>, Record<never, never>>,
    '/marketing/services': RouteRecordInfo<'/marketing/services', '/marketing/services', Record<never, never>, Record<never, never>>,
    '/marketing/services-detail': RouteRecordInfo<'/marketing/services-detail', '/marketing/services-detail', Record<never, never>, Record<never, never>>,
    '/members': RouteRecordInfo<'/members', '/members', Record<never, never>, Record<never, never>>,
    '/members/': RouteRecordInfo<'/members/', '/members', Record<never, never>, Record<never, never>>,
    '/members/comment-detail': RouteRecordInfo<'/members/comment-detail', '/members/comment-detail', Record<never, never>, Record<never, never>>,
    '/members/comments': RouteRecordInfo<'/members/comments', '/members/comments', Record<never, never>, Record<never, never>>,
    '/members/comments-detail': RouteRecordInfo<'/members/comments-detail', '/members/comments-detail', Record<never, never>, Record<never, never>>,
    '/members/info': RouteRecordInfo<'/members/info', '/members/info', Record<never, never>, Record<never, never>>,
    '/members/message-detail': RouteRecordInfo<'/members/message-detail', '/members/message-detail', Record<never, never>, Record<never, never>>,
    '/members/messages': RouteRecordInfo<'/members/messages', '/members/messages', Record<never, never>, Record<never, never>>,
    '/order': RouteRecordInfo<'/order', '/order', Record<never, never>, Record<never, never>>,
    '/order/': RouteRecordInfo<'/order/', '/order', Record<never, never>, Record<never, never>>,
    '/order/my-wallet': RouteRecordInfo<'/order/my-wallet', '/order/my-wallet', Record<never, never>, Record<never, never>>,
    '/promotion': RouteRecordInfo<'/promotion', '/promotion', Record<never, never>, Record<never, never>>,
    '/promotion/': RouteRecordInfo<'/promotion/', '/promotion', Record<never, never>, Record<never, never>>,
    '/promotion/coupons': RouteRecordInfo<'/promotion/coupons', '/promotion/coupons', Record<never, never>, Record<never, never>>,
    '/promotion/link': RouteRecordInfo<'/promotion/link', '/promotion/link', Record<never, never>, Record<never, never>>,
    '/promotion/rewards': RouteRecordInfo<'/promotion/rewards', '/promotion/rewards', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/settings/': RouteRecordInfo<'/settings/', '/settings', Record<never, never>, Record<never, never>>,
    '/settings/log': RouteRecordInfo<'/settings/log', '/settings/log', Record<never, never>, Record<never, never>>,
    '/settings/menu': RouteRecordInfo<'/settings/menu', '/settings/menu', Record<never, never>, Record<never, never>>,
    '/settings/permission': RouteRecordInfo<'/settings/permission', '/settings/permission', Record<never, never>, Record<never, never>>,
    '/settings/role': RouteRecordInfo<'/settings/role', '/settings/role', Record<never, never>, Record<never, never>>,
    '/settings/user': RouteRecordInfo<'/settings/user', '/settings/user', Record<never, never>, Record<never, never>>,
    '/tenant': RouteRecordInfo<'/tenant', '/tenant', Record<never, never>, Record<never, never>>,
    '/tenant/': RouteRecordInfo<'/tenant/', '/tenant', Record<never, never>, Record<never, never>>,
    '/tenant/license': RouteRecordInfo<'/tenant/license', '/tenant/license', Record<never, never>, Record<never, never>>,
    '/tenant/price': RouteRecordInfo<'/tenant/price', '/tenant/price', Record<never, never>, Record<never, never>>,
  }
}
